<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PwfAuthConsoleClient</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <!-- The official PWF Auth client: https://www.nuget.org/packages/PWFAuth -->
    <PackageReference Include="PWFAuth" Version="1.4.0" />
  </ItemGroup>

</Project>
